services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    networks:
      - spark-net

  spark:
    image: jupyter/pyspark-notebook:latest
    container_name: spark
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./data:/home/jovyan/work/data
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge:
